apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: webserver-deployment
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: webserver
        image: my-static-web
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:  
  namespace: default
  name: webserver-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 3000
      targetPort: 80
      nodePort: 31111
