name: b_testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  working-directory: ${{github.workspace}}/Task_B/RESTProj

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    container: node:10.18-jessie
    services:
      mongodb:
        image: mongo:3.6.8
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_INITDB_DATABASE: test
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


          
    steps:
    - uses: actions/checkout@v2
    
    - name: Check Path
      run: echo ${{env.working-directory}}
      
    - name: Configure Node.js and run
      uses: actions/setup-node@v2
        
    - run: npm ci 
      working-directory:  ${{env.working-directory}}/
      
    - run: npm test
      working-directory:  ${{env.working-directory}}/
      env:
        MONGO_HOST: mongo
        MONGO_PORT: 27017
