name: b_testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  working-directory: ${{github.workspace}}/Task B/B1/RESTProj

jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: Check Path
      run: echo ${{env.working-directory}}

    - name: Configure Node.js
      uses: actions/setup-node@v2
      with:
        cache: 'npm'
        
    - name: Run Test
      run: |
        cd ${{env.working-directory}}/
        npm install
        npm test
        

