name: b_testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  working-directory: ${{github.workspace}}/Task B/B1/RESTProj

jobs:
  build_and_test:
    runs-on: self-hosted
    
    container: node:10.18-jessie
    services:
      mongodb:
        image: mongo:3.6.8
        ports:
          - 27017:27017
          
    steps:
    - uses: actions/checkout@v2
    
    - name: Check Path
      run: echo ${{env.working-directory}}
      
    - name: Configure Node.js and run
      uses: actions/setup-node@v2
        
    - run: npm ci 
      working-directory:  ${{env.working-directory}}/
      
    - run: npm test
      working-directory:  ${{env.working-directory}}/


